// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    return $.fn.checkbox = function() {
      this.each(function() {
        var label, name_input, span, that;
        that = this;
        name_input = $(this).attr('name');
        $(this).css('display', 'none');
        if ($(this).attr('data-label') === void 0 || $(this).attr('data-label') === '') {
          label = 'label';
        } else {
          label = $(this).attr('data-label');
        }
        span = $(document.createElement('span'));
        span.addClass('checkbox_button');
        span.attr('data-name', name_input);
        span.text(label);
        span.on('click', function() {
          var nb_checked;
          if ($(that).is(':checked')) {
            span.removeClass('is_checked');
            return $(that).removeAttr('checked');
          } else {
            if ($(that).attr('type') === 'radio') {
              $('input[name="' + name_input + '"]').removeAttr('checked');
              $('span[data-name="' + span.attr('data-name') + '"]').removeClass('is_checked');
            }
            if ($(that).attr('type') === 'checkbox' && $(that).attr('data-answer-max') !== void 0) {
              nb_checked = $('input[name="' + name_input + '"][checked="checked"]').length;
              if (nb_checked < $(that).attr('data-answer-max')) {
                span.addClass('is_checked');
                return $(that).attr('checked', 'checked');
              } else {
                return $('body').wait({
                  state: 'show_message',
                  message: 'No more reponses are authorized',
                  time_out: 2000
                });
              }
            } else {
              span.addClass('is_checked');
              return $(that).attr('checked', 'checked');
            }
          }
        });
        return $(this).after(span);
      });
      return this;
    };
  });

}).call(this);
